### ISSUE TITLE
[🦄 Front-end 🦄] mypage 관련 html, css 기본작업하기

### ISSUE THREAD

**Issue by Youngseo-kangg** [MouseGamza/Todays-Chef#159]
# ISSUE
- Group:  `Front-End`
- Type:  `feature` 
- Detail: mypage 관련 html, css 기본작업하기

# TODO
1. [X] mypage html, css 기본작업
2. [x] mypage 내 컴포넌트 html, css 기본 작업
3. [x] mypage 내 컴포넌트에서 필요한 state작업하기
