### ISSUE TITLE
[🦄 Front-end 🦄] css 기본 rule 정하기

### ISSUE THREAD

**Issue by NAPP4287** [MouseGamza/Todays-Chef#29]
# ISSUE
- Group:  `Front-End`
- Type:  `feature`
- Detail: css 기본 rule 설정하기

# TODO
1. [x] media query 세분화 하기
2. [x] font-size, border-radius, border px, margin, 글씨체 정하기
3. [x] todayschef의 메인 컬러 세가지 뽑기
