### ISSUE TITLE
[🦄 Front-end 🦄] navBar 제작

### ISSUE THREAD

**Issue by Youngseo-kangg** [MouseGamza/Todays-Chef#33]
# ISSUE
- Group:  `Front-End`
- Type:  `feature` 
- Detail: navBar 제작 

# TODO
1. [x] navBar 유저 개인 메뉴 관련 태그 작성
2. [x] navBar css 작성
3. [x] 반응형 navBar 만들기
